# site settings
title: Pallavi Bhat
subtitle: Astrophysicist
email: palvi.b@gmail.com
description: Your description here!!!!
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Pallavi
street_address: Leeds university
city: 
state: 
zip_code: 
country: United Kingdom
phone: +44 7984 115050

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/palvib

# build settings
markdown: kramdown

sass:
  style: compressed
